apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-http
  template:
    metadata:
      labels:
        app: users-http
    spec:
      containers:
        - name: users-http
          image: samuel13/users-http:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: trailbox
            - name: DB_PASSWORD
              value: trailbox
            - name: DB_NAME
              value: trailbox
